# SPDX-License-Identifier: GPL-2.0-or-later
"""Real Chromium navigation; only the CHZZK document/provider responses are fake.

No header/cookie injection, CSP override, certificate bypass, native UI or live
provider claim. The existing service runs on explicit literal-loopback HTTP.
"""
from __future__ import annotations

import html
import base64
import json
import queue
import subprocess
import sys
import threading
from pathlib import Path
from urllib.parse import parse_qs, urlencode, urlsplit

from playwright.sync_api import Browser, expect, sync_playwright

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "browser-evidence"
OUT.mkdir(exist_ok=True)


class Fixture:
    def __init__(self) -> None:
        self.process = subprocess.Popen(
            ["node", "--experimental-strip-types", "tools/management-browser-fixture.mts"],
            cwd=ROOT, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL, text=True, encoding="utf-8",
        )
        self.lines: queue.Queue[str] = queue.Queue()
        def read() -> None:
            assert self.process.stdout
            for line in self.process.stdout:
                self.lines.put(line)
            self.lines.put("")
        threading.Thread(target=read, daemon=True).start()
        data = self.receive()
        assert data.get("ready") is True, "fixture ready"
        self.origin: str = data["origin"]
        assert self.origin.startswith("http://127.0.0.1:"), "private fixture origin"

    def receive(self) -> dict:
        data = json.loads(self.lines.get(timeout=10))
        assert "error" not in data, "server fixture invariants"
        return data

    def command(self, op: str) -> dict:
        assert self.process.stdin
        self.process.stdin.write(json.dumps({"op": op}) + "\n")
        self.process.stdin.flush()
        return self.receive()

    def close(self) -> None:
        if self.process.poll() is None:
            try:
                self.command("close")
                self.process.wait(timeout=5)
            except Exception:
                self.process.kill()
                self.process.wait(timeout=5)


class Flow:
    def __init__(self, browser: Browser, fixture: Fixture, width: int = 1000):
        self.f = fixture
        self.context = browser.new_context(viewport={"width": width, "height": 900})
        self.context.set_default_timeout(5000)
        self.page = self.context.new_page()
        self.page.set_default_navigation_timeout(10000)
        # Playwright route() only intercepts the first URL of a redirect chain.
        # Use its documented CDPSession for this narrow provider stub instead:
        # Fetch.requestPaused also exposes redirected requests. Service requests
        # continue unchanged; browser cookies/Origin/CSP are never overridden.
        self.network = self.context.new_cdp_session(self.page)
        self.network.on("Fetch.requestPaused", self.route)
        self.network.send("Fetch.enable", {"patterns": [{"urlPattern": "*", "requestStage": "Request"}]})

    def route(self, event: dict) -> None:
        request = event["request"]
        request_id = event["requestId"]
        url = urlsplit(request["url"])
        if request["url"].startswith(self.f.origin + "/"):
            self.network.send("Fetch.continueRequest", {"requestId": request_id})
            return
        if url.scheme == "https" and url.netloc == "chzzk.naver.com":
            headers = {key.lower(): value for key, value in request["headers"].items()}
            assert not headers.get("referer"), "service never sends an external Referer"
            assert not headers.get("authorization"), "provider page receives no native credential"
            state = parse_qs(url.query).get("state", [""])[0]
            assert len(state) == 64, "provider state generated by service"
            links = []
            for owner in ("alice", "bob", "charlie"):
                callback = self.f.origin + "/callback?" + urlencode({"state": state, "code": owner})
                links.append(f'<a id="{owner}" href="{html.escape(callback, quote=True)}">{owner}</a>')
            cancel = self.f.origin + "/callback?" + urlencode({"state": state, "error": "fixture-denied"})
            links += [f'<a id="cancel" href="{html.escape(cancel, quote=True)}">cancel</a>',
                      f'<a id="unrelated" href="{self.f.origin}/campaigns">unrelated</a>']
            body = ('<h1>Synthetic provider</h1>' + "<p>".join(links)).encode("utf-8")
            self.network.send("Fetch.fulfillRequest", {"requestId": request_id, "responseCode": 200,
                "responseHeaders": [{"name": "Content-Type", "value": "text/html; charset=utf-8"}],
                "body": base64.b64encode(body).decode("ascii")})
            return
        self.network.send("Fetch.failRequest", {"requestId": request_id, "errorReason": "BlockedByClient"})

    def cookie(self) -> str:
        cookies = [c for c in self.context.cookies() if c["name"] == "__Host-chatview"]
        assert len(cookies) == 1, "browser accepted exactly one host cookie"
        cookie = cookies[0]
        assert cookie["secure"] and cookie["httpOnly"], "secure HttpOnly cookie"
        assert cookie["sameSite"] == "Lax" and cookie["path"] == "/", "cookie scope"
        assert cookie["domain"] == "127.0.0.1", "host-only cookie"
        assert "__Host-chatview" not in self.page.evaluate("document.cookie"), "HttpOnly isolation"
        return cookie["value"]

    def start(self, path: str) -> None:
        self.page.goto(self.f.origin + path)
        expect(self.page.locator("h1")).to_have_text("브라우저 관리 로그인")
        self.cookie()
        self.page.get_by_role("button", name="치지직으로 브라우저 로그인", exact=True).click()
        expect(self.page.locator("h1")).to_have_text("Synthetic provider")

    def identity(self, path: str, owner: str = "alice") -> None:
        self.start(path)
        old = self.cookie()
        with self.page.expect_response(lambda r: urlsplit(r.url).path == "/account/confirm") as arrival:
            self.page.locator("#" + owner).click()
        assert arrival.value.status == 200, f"callback landing returned {arrival.value.status}"
        expect(self.page.locator("h1")).to_have_text("관리할 채널 확인")
        expect(self.page.locator("body")).to_contain_text(f"channel <{owner}>")
        assert self.cookie() != old, "callback rotates anonymous identity"

    def confirm(self, path: str, owner: str = "alice") -> None:
        old = self.cookie()
        self.page.get_by_role("button", name="이 채널로 관리 계속", exact=True).click()
        expect(self.page).to_have_url(self.f.origin + path)
        expect(self.page.get_by_role("region", name="브라우저 관리 계정")).to_contain_text(f"channel <{owner}>")
        assert self.cookie() != old, "explicit confirmation rotates identity again"

    def image(self, name: str) -> None:
        assert self.page.evaluate("document.documentElement.scrollWidth <= innerWidth"), "no horizontal overflow"
        self.page.screenshot(path=str(OUT / (name + ".png")), full_page=True)

    def close(self) -> None:
        self.context.close()


def run() -> None:
    f = Fixture()
    results: list[str] = []
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            try:
                for index, path in enumerate(("/account", "/campaigns", "/campaigns/activity")):
                    flow = Flow(browser, f, 390 if index == 1 else 1000)
                    try:
                        flow.identity(path)
                        if index == 1:
                            flow.image("channel-confirmation-mobile")
                        flow.confirm(path)
                        if path == "/campaigns":
                            # Browser/CSP really execute the fixed copy helper;
                            # no service credentials or private messages are copied.
                            source = flow.page.locator("#source-url")
                            assert source.get_attribute("readonly") is not None
                            public_url = source.input_value()
                            assert public_url.startswith(f.origin + "/public/ads/")
                            assert len(public_url.rsplit("/", 1)[-1]) == 32
                            expect(flow.page.locator('[data-public-banner-state="waiting-report"]')).to_have_count(1)
                            flow.context.grant_permissions(["clipboard-read", "clipboard-write"], origin=f.origin)
                            copy = flow.page.get_by_role("button", name="공개 주소 복사")
                            copy.click()
                            expect(flow.page.locator("#copy-public-result")).to_have_text(
                                "공개 배너 주소를 복사했습니다. OBS의 URL 칸에 붙여넣으세요.")
                            assert flow.page.evaluate("navigator.clipboard.readText()") == public_url
                            # Deterministic browser clipboard denial exercises
                            # keyboard selection fallback; the public URL and
                            # server/CSRF state remain unchanged.
                            flow.page.evaluate("""() => Object.defineProperty(navigator, 'clipboard', {
                                configurable: true, value: {writeText: () => Promise.reject(new Error('blocked'))}
                            })""")
                            copy.click()
                            expect(flow.page.locator("#copy-public-result")).to_contain_text("Ctrl+C")
                            assert source.evaluate("(el) => el.selectionStart === 0 && el.selectionEnd === el.value.length")
                            expect(flow.page.get_by_role("heading", name="OBS 공개 시험 배너 연결")).to_have_count(1)
                            # Follow the evidence explanation from the campaign setup,
                            # then return without changing the source address or consent.
                            flow.page.get_by_role("link", name="비지급 활동 기록 · 근거 구분 보기").click()
                            expect(flow.page).to_have_url(f.origin + "/campaigns/activity")
                            for stage in ("output", "audience", "exposure"):
                                expect(flow.page.locator(f'[data-evidence-stage="{stage}"]')).to_have_count(1)
                            expect(flow.page.locator('[data-evidence-state="not-measured"]')).to_have_count(1)
                            flow.page.get_by_role("link", name="캠페인 선택·중지").click()
                            expect(flow.page).to_have_url(f.origin + "/campaigns")
                            assert source.input_value() == public_url, "evidence navigation cannot change public OBS URL"
                            results.append("selected campaign copies public OBS URL and returns from private evidence intact")
                        elif path == "/account":
                            # The fixture keeps one Alice streaming-role peer open.
                            # Its gaming approval count is zero; Bob's distinct
                            # gaming approval must never show on Alice's page.
                            expect(flow.page.get_by_role("heading",
                                name="이 계정의 PC 역할·현재 채팅 연결")).to_have_count(1)
                            gamer = flow.page.locator('[data-pc-role="gaming"]')
                            sender = flow.page.locator('[data-pc-role="streaming"]')
                            expect(gamer.locator('[data-approved-count]')).to_have_attribute("data-approved-count", "0")
                            expect(gamer.locator('[data-online-count]')).to_have_attribute("data-online-count", "0")
                            expect(sender.locator('[data-approved-count]')).to_have_attribute("data-approved-count", "1")
                            expect(sender.locator('[data-online-count]')).to_have_attribute("data-online-count", "1")
                            expect(flow.page.locator('[data-output-report="unknown"]')).to_have_count(1)
                            expect(flow.page.locator("#two-pc-status")).to_contain_text("게임 PC에서는 OBS 없이")
                            expect(flow.page.locator("#two-pc-status")).to_contain_text("현재 승인으로 자체 채팅 복귀")
                            flow.page.get_by_role("link", name="현재 연결 다시 확인").click()
                            expect(sender.locator('[data-online-count]')).to_have_attribute("data-online-count", "1")
                            results.append("owner roles, server socket presence and explicit native return are distinct")
                        elif path == "/campaigns/activity":
                            for stage in ("output", "audience", "exposure"):
                                expect(flow.page.locator(f'[data-evidence-stage="{stage}"]')).to_have_count(1)
                            for state in ("no-reports", "unmeasured", "not-measured"):
                                expect(flow.page.locator(f'[data-evidence-state="{state}"]')).to_have_count(1)
                            flow.page.get_by_role("link", name="2. 채널 시청자 추정").click()
                            assert flow.page.evaluate("location.hash") == "#activity-audience"
                            results.append("owner-only evidence stages and in-page navigation are readable in Chromium")
                        else:
                            expect(flow.page.locator("#copy-public-source")).to_have_count(0)
                        flow.image("management-" + str(index))
                        assert f.command("check")["ok"]
                        results.append("browser round trip: " + path)
                    finally:
                        flow.close()

                flow = Flow(browser, f)
                try:
                    flow.identity("/campaigns")
                    flow.page.get_by_role("button", name="취소", exact=True).click()
                    expect(flow.page.locator("h1")).to_have_text("브라우저 관리 로그인")
                    flow.page.go_back()
                    expect(flow.page.locator("h1")).to_have_text("브라우저 로그인 확인 만료")
                    expect(flow.page.get_by_role("button", name="이 채널로 관리 계속", exact=True)).to_have_count(0)
                    assert f.command("check")["ok"]
                    results.append("cancel and browser back cannot revive confirmation")

                    flow.identity("/account")
                    flow.confirm("/account")
                    flow.page.get_by_role("button", name="브라우저 관리 계정 바꾸기", exact=True).click()
                    expect(flow.page.locator("h1")).to_have_text("브라우저 관리 로그인")
                    flow.page.go_back()
                    expect(flow.page.get_by_role("region", name="브라우저 관리 계정")).to_have_count(0)
                    flow.identity("/campaigns", "bob")
                    flow.confirm("/campaigns", "bob")
                    assert "channel <alice>" not in flow.page.locator("body").inner_text(), "old account not presented"
                    assert f.command("check")["ok"]
                    results.append("account switch and back leave both native approvals intact")
                finally:
                    flow.close()

                flow = Flow(browser, f)
                try:
                    flow.identity("/campaigns")
                    flow.confirm("/campaigns")
                    f.command("expire-browser")
                    flow.page.locator('form[action="/campaigns/stop"] button').click()
                    expect(flow.page.locator("h1")).to_have_text("관리 로그인 필요")
                    expect(flow.page.locator("body")).to_contain_text("자동으로 다시 실행하지 않습니다")
                    flow.page.get_by_role("link", name="관리 로그인으로 돌아가기").click()
                    expect(flow.page.locator("h1")).to_have_text("브라우저 관리 로그인")
                    flow.image("expired-browser-recovery")
                    flow.identity("/account")
                    flow.confirm("/account")
                    assert f.command("check")["ok"]
                    results.append("expired form is not replayed after browser recovery")

                    flow.page.get_by_role("button", name="브라우저 관리 계정 바꾸기", exact=True).click()
                    flow.start("/account")
                    flow.page.locator("#cancel").click()
                    expect(flow.page.locator("h1")).to_have_text("브라우저 로그인 미완료")
                    flow.page.get_by_role("link", name="관리 로그인으로 돌아가기").click()
                    flow.identity("/account")
                    f.command("expire-confirmation")
                    flow.page.get_by_role("button", name="이 채널로 관리 계속", exact=True).click()
                    expect(flow.page.locator("h1")).to_have_text("관리 로그인 필요")
                    assert f.command("check")["ok"]
                    results.append("provider cancellation and expired confirmation have no authority")
                finally:
                    flow.close()

                flow = Flow(browser, f)
                try:
                    flow.start("/account")
                    with flow.page.expect_response(lambda r: urlsplit(r.url).path == "/campaigns") as denied:
                        flow.page.locator("#unrelated").click()
                    assert denied.value.status == 403, "unrelated cross-site navigation remains forbidden"
                    assert f.command("check")["ok"]
                    results.append("cross-site exception cannot open an unrelated page")
                finally:
                    flow.close()

                flow = Flow(browser, f)
                try:
                    pending = f.command("native-start")
                    flow.page.goto(f.origin + pending["path"])
                    flow.page.get_by_role("button", name="치지직으로 로그인", exact=True).click()
                    expect(flow.page.locator("h1")).to_have_text("Synthetic provider")
                    with flow.page.expect_response(lambda r: urlsplit(r.url).path == pending["path"]) as arrival:
                        flow.page.locator("#charlie").click()
                    assert arrival.value.status == 200, "native consent callback landing"
                    expect(flow.page.locator("h1")).to_have_text("챗뷰에 채팅 연결")
                    flow.page.get_by_role("button", name="이 채널과 요청 역할로 연결", exact=True).click()
                    expect(flow.page.locator("h1")).to_have_text("연결 요청 처리됨")
                    assert f.command("native-collect")["ok"]
                    assert f.command("check")["ok"]
                    results.append("native login shares the valid callback landing without automatic approval")
                finally:
                    flow.close()

                flow = Flow(browser, f, 390)
                try:
                    flow.identity("/campaigns")
                    flow.confirm("/campaigns")
                    public_url = flow.page.locator("#source-url").input_value()
                    public = flow.context.new_page()
                    public.goto(public_url)
                    banner = public.locator("#banner")
                    expect(banner).to_be_hidden()
                    recovery = flow.page.locator("[data-banner-recovery-state]")
                    expect(recovery).to_have_attribute("data-banner-recovery-state", "waiting-report")

                    assert f.command("sender-disconnect")["ok"]
                    flow.page.get_by_role("link", name="현재 상태 새로고침", exact=True).click()
                    expect(recovery).to_have_attribute("data-banner-recovery-state", "streaming-disconnected")
                    expect(recovery).to_contain_text("현재 승인으로 자체 채팅 복귀")
                    flow.page.get_by_role("link", name="송출 승인·현재 연결 확인", exact=True).click()
                    sender = flow.page.locator('[data-pc-role="streaming"]')
                    expect(sender.locator('[data-approved-count]')).to_have_attribute("data-approved-count", "1")
                    expect(sender.locator('[data-online-count]')).to_have_attribute("data-online-count", "0")
                    flow.page.get_by_role("link", name="시험 캠페인 선택 · OBS 공개 배너", exact=True).click()
                    expect(recovery).to_have_attribute("data-banner-recovery-state", "streaming-disconnected")
                    flow.image("banner-recovery-disconnected-mobile")

                    # Only parent-controlled native HTTP renews the same approval.
                    # Browser navigation has no login/output/select capability.
                    assert f.command("sender-return")["ok"]
                    flow.page.get_by_role("link", name="현재 상태 새로고침", exact=True).click()
                    expect(recovery).to_have_attribute("data-banner-recovery-state", "waiting-report")
                    expect(recovery).to_contain_text("방송·녹화를 시작할 필요는 없습니다")
                    expect(banner).to_be_hidden()
                    assert f.command("sender-report")["ok"]
                    flow.page.get_by_role("link", name="현재 상태 새로고침", exact=True).click()
                    expect(recovery).to_have_attribute("data-banner-recovery-state", "report-ready")
                    expect(banner).to_be_visible()
                    expect(public.locator("#title")).to_have_text("방송과 함께하는 챗뷰")

                    assert f.command("expire-output-report")["ok"]
                    flow.page.get_by_role("link", name="현재 상태 새로고침", exact=True).click()
                    expect(recovery).to_have_attribute("data-banner-recovery-state", "waiting-report")
                    expect(banner).to_be_hidden()
                    assert f.command("sender-report")["ok"]
                    flow.page.get_by_role("link", name="현재 상태 새로고침", exact=True).click()
                    expect(recovery).to_have_attribute("data-banner-recovery-state", "report-ready")
                    expect(banner).to_be_visible()
                    assert flow.page.locator("#source-url").input_value() == public_url
                    expect(public).to_have_url(public_url)
                    flow.page.get_by_role("link", name="기존 공개 소스 설정 보기", exact=True).click()
                    assert flow.page.evaluate("location.hash") == "#obs-source-setup"
                    flow.image("banner-recovery-ready-mobile")
                    assert f.command("check")["ok"]
                    results.append("same-approval sender recovery and report expiry restore the same public document without reselection")
                finally:
                    flow.close()

                flow = Flow(browser, f, 390)
                try:
                    flow.identity("/campaigns")
                    flow.confirm("/campaigns")
                    public_url = flow.page.locator("#source-url").input_value()
                    public = flow.context.new_page()
                    public.goto(public_url)
                    banner = public.locator("#banner")
                    expect(banner).to_be_visible()

                    pending = f.command("conflict-start")
                    flow.page.goto(f.origin + pending["path"])
                    with flow.page.expect_response(lambda r: urlsplit(r.url).path == pending["path"] + "/approve") as denied:
                        flow.page.get_by_role("button", name="이 채널과 요청 역할로 연결", exact=True).click()
                    assert denied.value.status == 409, "conflict remains an HTTP conflict, not a false success"
                    expect(flow.page.locator("h1")).to_have_text("이미 승인된 송출 연결이 있습니다")
                    expect(flow.page.get_by_role("region", name="기존 송출 승인")).to_contain_text(pending["connectionId"])
                    flow.image("streaming-conflict-mobile")
                    flow.page.get_by_role("button", name="새 송출 요청 취소", exact=True).click()
                    assert f.command("conflict-cancelled")["ok"]
                    flow.page.get_by_role("link", name="내 연결 관리", exact=True).click()
                    expect(flow.page.locator("[data-streaming-request]")).to_have_count(0)
                    assert f.command("check")["ok"]
                    expect(banner).to_be_visible()
                    results.append("cancelled conflicting sender request preserves existing approval and public banner")

                    pending = f.command("conflict-start")
                    flow.page.goto(f.origin + pending["path"])
                    flow.page.get_by_role("button", name="이 채널과 요청 역할로 연결", exact=True).click()
                    expect(flow.page.locator("[data-streaming-conflict]")).to_have_count(1)
                    flow.page.get_by_role("link", name="기존 송출 연결 확인·해제", exact=True).click()
                    expect(flow.page).to_have_url(f.origin + "/account#approved-connections")
                    notice = flow.page.get_by_role("region", name="돌아갈 송출 승인 요청")
                    expect(notice).to_contain_text(pending["path"].rsplit("/", 1)[-1][-6:].upper())
                    # Use the existing owner-scoped CSRF form, not a fixture
                    # delete or a new automatic transfer endpoint.
                    flow.page.locator(f'form[action="/connections/{pending["connectionId"]}/revoke"] button').click()
                    expect(flow.page).to_have_url(f.origin + "/account")
                    assert f.command("conflict-released")["ok"]
                    expect(banner).to_be_hidden()
                    sender = flow.page.locator('[data-pc-role="streaming"]')
                    expect(sender.locator('[data-approved-count]')).to_have_attribute("data-approved-count", "0")
                    flow.page.get_by_role("link", name="원래 송출 승인 요청으로 돌아가기", exact=True).click()
                    expect(flow.page).to_have_url(f.origin + pending["path"])
                    expect(flow.page.locator("h1")).to_have_text("챗뷰에 채팅 연결")
                    flow.page.get_by_role("button", name="이 채널과 요청 역할로 연결", exact=True).click()
                    expect(flow.page.locator("h1")).to_have_text("연결 요청 처리됨")
                    assert f.command("conflict-collect")["ok"]
                    flow.page.get_by_role("link", name="내 연결 관리", exact=True).click()
                    expect(flow.page.locator("[data-streaming-request]")).to_have_count(0)
                    flow.page.get_by_role("link", name="시험 캠페인 선택 · OBS 공개 배너", exact=True).click()
                    expect(flow.page.locator('[data-public-banner-state="not-selected"]')).to_have_count(1)
                    assert f.command("sender-report")["ok"]
                    flow.page.get_by_role("link", name="현재 상태 새로고침", exact=True).click()
                    expect(flow.page.locator('[data-public-banner-state="not-selected"]')).to_have_count(1)
                    expect(banner).to_be_hidden()
                    assert flow.page.locator("#source-url").input_value() == public_url
                    flow.page.get_by_role("button", name="이 시험 캠페인 선택", exact=True).click()
                    expect(flow.page.locator('[data-public-banner-state="report-ready"]')).to_have_count(1)
                    expect(banner).to_be_visible()
                    expect(public).to_have_url(public_url)
                    assert flow.page.locator("#source-url").input_value() == public_url
                    assert f.command("conflict-selected")["ok"]
                    flow.image("streaming-conflict-reselected-mobile")
                    results.append("owner releases only the old sender, returns to original consent and explicitly reselects the same public source")
                finally:
                    flow.close()

                metadata = f.command("metadata")["metadata"]
                returns = [r for r in metadata if r["path"] in ("/callback", "/account/confirm", "/login/:id")
                           and r["site"] == "cross-site"]
                assert any(r["path"] == "/callback" and r["cookie"] for r in returns), "real cross-site callback cookie"
                assert any(r["path"] == "/account/confirm" and r["status"] == 200 for r in returns), "actual tainted redirect chain"
                assert all(not r["authorization"] for r in returns), "no native credential bridge"
                (OUT / "result.json").write_text(json.dumps({"browser": browser.version, "scenarios": results,
                    "requests": metadata, "provider": "synthetic", "transport": "loopback HTTP"},
                    ensure_ascii=False, indent=2), encoding="utf-8")
                print(f"Management browser flow: {len(results)}/{len(results)} passed (synthetic provider)")
            finally:
                browser.close()
    except Exception as error:
        try:
            (OUT / "failure-metadata.json").write_text(json.dumps(f.command("metadata"), indent=2), encoding="utf-8")
        except Exception:
            pass
        if isinstance(error, AssertionError):
            print(str(error), file=sys.stderr)
        else:
            print(type(error).__name__ + ": browser flow failed; no sensitive diagnostics exported", file=sys.stderr)
        raise SystemExit(1) from None
    finally:
        f.close()


if __name__ == "__main__":
    run()
