name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm install
      - run: npm install -g electron-builder  # electron-builder 설치
      - name: Build and Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            npm run build && electron-builder build --mac --publish always
          else
            npm run build && electron-builder build --win --publish always
          fi
        shell: bash